project: "VAE-MNIST"
tags: "first-run"
seed: 41

models:
  name: "VAE"
  args:
    encoder:
      name: "VEncoder"
      args:
        in_channels: 1
        latent_dim: 64
        hidden_channels: [8, 16, 32, 64, 128]
    decoder:
      name: "VDecoder"
      args:
        out_channels: 1
        latent_dim: 64
        hidden_channels: [64, 32, 16, 8]
    weight_recon: 1
    weight_reg: 0.0001

data:
  name: "MNISTDataModule"
  args:
    root: "./"   # path to the root directory
    batch_size: 1024
    shuffle: True
    num_workers: 0  # for mac
    on_gpu: False   # pin memory

trainer:
  name: "VAETrainer"
  args:
    max_epochs: 100
    optimizer:
      name: "AdamW"
      args:
        lr: 0.001
        weight_decay: 0.0
    sample_epoch: 5  # saves a few samples at the end of each epoch
    device: "mps"
    checkpoint_dir: "./ckpts/"
    track: "loss"
    clip_grad: False
    